import cyber from "./assets/cyber.jpeg";
import web from "./assets/web.png";
import wordpress from "./assets/wordpress.jpeg";
export const projects = [
	{
		id: 1,
		img: cyber,
		category: "Cyber Security",
		title: "1 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 1500,
	},
	{
		id: 2,
		img: cyber,
		category: "Cyber Security",
		title: "3 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 3000,
		newprice: 2799,
	},
	{
		id: 3,
		img: cyber,
		category: "Cyber Security",
		title: "6 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 6000,
		newprice: 4299,
	},
	{
		id: 4,
		img: web,
		category: "Web Technology",
		title: "1 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 1000,
	},
	{
		id: 5,
		img: web,
		category: "Web Technology",
		title: "3 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 3000,
		newprice: 2499,
	},
	{
		id: 6,
		img: web,
		category: "Web Technology",
		title: "6 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 6000,
		newprice: 3999,
	},
	{
		id: 7,
		img: wordpress,
		category: "WordPress",
		title: "1 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 1000,
	},
	{
		id: 8,
		img: wordpress,
		category: "WordPress",
		title: "3 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 3000,
		newprice: 2499,
	},
	{
		id: 9,
		img: wordpress,
		category: "WordPress",
		title: "6 Month Course",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
		price: 6000,
		newprice: 3999,
	},
];
